### ISSUE TITLE
Containerizing the App

### ISSUE THREAD

**Issue by paulcalabro** [howardchung/jeopardy#53]
I'm looking to containerize the app. I can't quite seem to get the paged to load, however. 

I started to create a Dockerfile:

```
FROM node:19.9.0-alpine3.17

WORKDIR /app

COPY . .

RUN npm install && \
    npm run buildServer

ENTRYPOINT ["npm", "run", "server"]

EXPOSE 8080
```

as well as an accompanying Compose file:

```
---

services:
  application:
    build: services/application
    ports:
      - "8080:8080/tcp"
```

While I can hit the following endpoints successfully:

- /ping
- /createRoom

I can't get the app to load.

Any tips or pointers on what I'm missing?

Thanks!
